services:
  app:
    stdin_open: true
    build:
      context: "./app"
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  database:
    build:
      context: "./db"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db/dbdata:/var/lib/mysql/

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: toor

  server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - "7000:8888"